# Filename: docker-compose.yml

version: "3.8"
services:
  apache:
    container_name: nmt_apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "8181:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs

  php:
    container_name: nmt_php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
